### ISSUE TITLE
[Feature Request] Note folder options

### ISSUE THREAD

**Issue by Tony-zf1** [SimonTC/obsidian-note-autocreation#1]
Thanks for your plugin !

During my trial, I found conflicts between **this plugin** and **various complements**. I don't know whether this problem can be solved.

And i think it's excellent to have note folder options like **root directory** or **same with current note**. 

Thanks again !

**Comment by SimonTC** [comment]
Thanks for the request. 

> During my trial, I found conflicts between this plugin and various complements. I don't know whether this problem can be solved.

Can you explain the conflicts between this plugin and various complements? I am not a user of various complements myself, but I did some quick testing to see how it works. 
Is the issue that when writing a link you do not get the auto-completion from various complements? Unfortunately, if that is the case, I am not sure we can do anything about it since both plugins rely on a dropdown and I do not think it is possible to have multiple drop-downs active at the same time. 

> And i think it's excellent to have note folder options like root directory or same with current note.
Can you give some more details about this or an example?

**Comment by Tony-zf1** [comment]
Thanks for reply.

> I do not think it is possible to have multiple drop-downs active at the same time.

All right, then I  can just turn off various complements. 

> And i think it's excellent to have note folder options like root directory or same with current note.

In the latest version, the new note will be created in the vault folded by default. But in some cases, I want the newly created note  to be in the same folder as the current active note. 

So it's excellent to have an option on note location in the plugin settings like the picture below.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/79450935/168513820-f40e44ef-9ad0-46d6-a03d-339d9603a1f2.png">

**Comment by SimonTC** [comment]
Ah yes, that makes a lot of sense.  I will make this plugin follow the settings chosen there.

**Comment by SimonTC** [comment]
@Tony-zf1 it is done.
In version 1.1.0 the plugin now respects the default location for new notes.
